[View in Colaboratory](https://colab.research.google.com/github/ejabril/nltk-training/blob/master/1_numpy.ipynb)

In [15]:
subjects = ['match','science','english','cs']
subjects[2] = 'English'
subjects.append('filipino')

scientist = {'Name':'Alan Turing',
             'Field':'Mathematics'

['match', 'science', 'English', 'cs', 'filipino']


In [30]:
import numpy as np
x = np.array([1,2,3,4,5])
a = np.zeros((2,2))
b = np.ones((2,2))
c = np.random.randint(10,size =(5))
d = np.random.random((2,2))

print(np.sum(x))

15


In [40]:
import numpy as np
a = np.random.randint(58,size =(6))
b = np.random.randint(10,size =(5))

print(a)

[48 23 14 15 39 48]


In [81]:
#Exercise Numpy
import numpy as np
A = np.matrix([[22,5,16,9]
              ,[13,20,19,0]
              ,[5,9,1,16] 
              ,[27,13,15,19]
              ])
B = np.matrix([[10,5,20,20]
              ,[5,21,22,27]
              ,[26,19,22,3]
              ,[27,8,18,7]
              ])
c = [24,3,17,7,11,2,21,2,24,18,3,11,14,25,2,20]
d = [3,15,24,22,19,24,4,29,6,3,20,1,11,25,26,6]

#1
print('Number 1:')
print(np.add(A,B))
#2
print('Number 2:')
print(np.subtract(A,B))
#3
print('Number 3:')
print(np.multiply(A,B))
#4
print('Number 4:')
print(np.matmul(A,B))
#5
print('Number 5:')
print(np.add(c,d))
#6
print('Number 6:')
print(np.subtract(c,d))
#7
print('Number 7:')
print(np.multiply(c,d))
#8
print('Number 8:')
print(np.matmul(c,d))
#9
print('Number 9:')
print(np.add(A,10))
#10
print('Number 10:')
print(np.add(B,10))
#11
print('Number 11:')
print(np.add(c,15))
#12
print('Number 12:')
print(np.add(d,15))
#13
print('Number 13:')
print(np.add(np.multiply(2,A),np.multiply(2,B)))
#14
print('Number 14:')
print(np.multiply(np.add(A,B),3))
#15
print('Number 15:')
print((A - B + A -B + B)*4)

Number 1:
[[32 10 36 29]
 [18 41 41 27]
 [31 28 23 19]
 [54 21 33 26]]
Number 2:
[[ 12   0  -4 -11]
 [  8  -1  -3 -27]
 [-21 -10 -21  13]
 [  0   5  -3  12]]
Number 3:
[[220  25 320 180]
 [ 65 420 418   0]
 [130 171  22  48]
 [729 104 270 133]]
Number 4:
[[ 904  591 1064  686]
 [ 724  846 1118  857]
 [ 553  361  608  458]
 [1238  845 1498 1069]]
Number 5:
[27 18 41 29 30 26 25 31 30 21 23 12 25 50 28 26]
Number 6:
[ 21 -12  -7 -15  -8 -22  17 -27  18  15 -17  10   3   0 -24  14]
Number 7:
[ 72  45 408 154 209  48  84  58 144  54  60  11 154 625  52 120]
Number 8:
2298
Number 9:
[[32 15 26 19]
 [23 30 29 10]
 [15 19 11 26]
 [37 23 25 29]]
Number 10:
[[20 15 30 30]
 [15 31 32 37]
 [36 29 32 13]
 [37 18 28 17]]
Number 11:
[39 18 32 22 26 17 36 17 39 33 18 26 29 40 17 35]
Number 12:
[18 30 39 37 34 39 19 44 21 18 35 16 26 40 41 21]
Number 13:
[[ 64  20  72  58]
 [ 36  82  82  54]
 [ 62  56  46  38]
 [108  42  66  52]]
Number 14:
[[ 96  30 108  87]
 [ 54 123 123  81]
 [ 93  84  69  57]
 [16